[package]
name = "puzzleverse-client"
version = "0.1.0"
authors = ["Andre Masella <andre@masella.name>"]
edition = "2018"
crate-type = ["bin"]

[dependencies]
amethyst = "0.13.0"
puzzleverse-core = { path = "../core" }
puzzleverse-client-core = { path = "../clientcore" }
