[package]
name = 'puzzleverse-client'
version = '0.1.0'
authors = ['Andre Masella <andre@masella.name>']
edition = '2018'

[dependencies]
async-trait = '^0.1'
derivative = '^2.2'
futures = '^0.3'
futures-sink = '^0.3'
gfx = '^0.18'
gfx-hal = '^0.5'
rmp = '^0.8'
rmp-serde = '^0.14'
serde_json = '1.0'
three-d = '^0.3'

[dependencies.puzzleverse-core]
path = '../core'

[dependencies.serde]
version = '^1.0'
features = ['derive']
[target."cfg(not(target_arch = \"wasm32\"))".dependencies]
alerts = '^0.1'
argparse = '^0.2'
bytes = '^1.0'
directories = '^3.0'
gfx-backend-vulkan = '^0.5'
http = '^0.2'
hyper-native-tls = '^0.3'
hyper-tls = '^0.5'
rand = '^0.8'
tokio = '^1.0'
tokio-tungstenite = '^0.13'
tungstenite = '^0.12'

[target."cfg(not(target_arch = \"wasm32\"))".dependencies.hyper]
version = '^0.14'
features = [
    'client',
    'http2',
]

[target."cfg(not(target_arch = \"wasm32\"))".dependencies.iced]
git = 'https://github.com/hecrj/iced.git'
features = ['tokio']

[target."cfg(not(target_arch = \"wasm32\"))".dependencies.iced_futures]
git = 'https://github.com/hecrj/iced.git'
features = ['tokio']

[target."cfg(not(target_arch = \"wasm32\"))".dependencies.iced_native]
git = 'https://github.com/hecrj/iced.git'
[target."cfg(target_arch = \"wasm32\")".dependencies]
wasm-bindgen = '^0.2'

[target."cfg(target_arch = \"wasm32\")".dependencies.iced]
git = 'https://github.com/hecrj/iced.git'

[target."cfg(target_arch = \"wasm32\")".dependencies.stdweb]
version = '^0.4'
features = ['futures-support']
