[package]
name = 'puzzleverse-core'
version = '0.1.0'
authors = ['Andre Masella <andre@masella.name>']
edition = '2018'

[dependencies]
gltf = '^0.15'
rmp-serde = '^0.15'

[dependencies.chrono]
version = '^0.4'
features = ['serde']

[dependencies.serde]
version = '^1.0'
features = ['derive']
